name: Build

env:
  PACKAGE_NAME: 'Noldova.AI.Parsers.Text'

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
        include-prerelease: True
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet build src/${{env.PACKAGE_NAME}}/${{env.PACKAGE_NAME}}.csproj --configuration Release